spring:
  application:
    name: virtual-thread-app
  threads:
    virtual:
      enabled: true
  profiles:
    active: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/vt
    username: root
    password: 1234
    hikari:
      maximum-pool-size: 100
      minimum-idle: 100
  jpa:
    hibernate:
      ddl-auto: create-drop
management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  metrics:
    enable:
      jvm: true
      system: true
      process: true
